### PR TITLE
Added obsolete State error and field

### PR DESCRIPTION
**Pull request by Bertverbeek4PS**
Obsoleted fields you cannot export. So you need also an error when you select a field that is obsoleted.

### CODE REVIEW

**Comment by pri-kise** [comment]
@Bertverbeek4PS why shouln't obsolete pending fields being able to be exported?

**Comment by Bertverbeek4PS** [comment]
> @Bertverbeek4PS why shouln't obsolete pending fields being able to be exported?

You are right! Only removed fields cannot be exported. Have changed it. Thanks!

**Comment by DuttaSoumya** [comment]
Good find. May I please request that you change the following line at https://github.com/microsoft/bc2adls/blob/main/.assets/Execution.md
image
to,
**BLOB, Flow and Filter fields as well as the fields that have been Obsoleted are not supported.**

**Comment by Bertverbeek4PS** [comment]
> Good find. May I please request that you change the following line at https://github.com/microsoft/bc2adls/blob/main/.assets/Execution.md image to, **BLOB, Flow and Filter fields as well as the fields that have been Obsoleted are not supported.**

Changed the text.

**Pull request merged**
